// Code generated by Slice Machine. DO NOT EDIT.

import Animation from './Animation';
import HeroSlice from './HeroSlice';
import NavigationItem from './NavigationItem';
import OtherPages from './OtherPages';
import Projects from './Projects';
import Resources from './Resources';
import WhatIOffer from './WhatIOffer';

export {
	Animation,
	HeroSlice,
	NavigationItem,
	OtherPages,
	Projects,
	Resources,
	WhatIOffer,
};

export const components = {
	animation: Animation,
	hero_slice: HeroSlice,
	navigation_item: NavigationItem,
	other_pages: OtherPages,
	projects: Projects,
	resources: Resources,
	what_i_offer: WhatIOffer,
};
