// Code generated by Slice Machine. DO NOT EDIT.

import Animation from './Animation';
import HeroSlice from './HeroSlice';
import OtherPages from './OtherPages';
import Projects from './Projects';
import WhatIOffer from './WhatIOffer';

export {
	Animation,
	HeroSlice,
	OtherPages,
	Projects,
	WhatIOffer,
};

export const components = {
	animation: Animation,
	hero_slice: HeroSlice,
	other_pages: OtherPages,
	projects: Projects,
	what_i_offer: WhatIOffer,
};
